import { Item } from 'src/types/apps/operationType'

export const CHECKLIST: Item[] = [
  {
    id: 'aoi-touch',
    title: 'Toque / Rejeição em AOI (Weekly/Daily)',
    description:
      'Preço reagindo em AOI no Weekly/Daily (ex.: martelo, engulfing)',
    group: 'Análise',
    weight: 15,
  },
  {
    id: 'psych-level',
    title: 'Nível psicológico (Weekly/Daily)',
    description:
      'Níveis redondos (ex.: 1.20000). Confluência extra se coincidir com AOI',
    group: 'Análise',
    weight: 10,
  },
  {
    id: 'ema-touch',
    title: 'Toque / Rejeição na EMA 50',
    description: 'EMA50 atuando como suporte/resistência dinâmica',
    group: 'Análise',
    weight: 10,
  },
  {
    id: 'candle-rejection',
    title: 'Rejeição por padrão de candle',
    description: 'Pin bar, martelo, martelo invertido, engulfing',
    group: 'Análise',
    weight: 10,
  },
  {
    id: 'prev-structure',
    title: 'Rejeição na estrutura anterior',
    description: 'Preço reagindo em topos/fundos anteriores',
    group: 'Análise',
    weight: 10,
  },
  {
    id: 'patterns',
    title: 'Padrões/gráficos',
    description: 'Topo/Fundo duplo, OCO, rompimento e reteste',
    group: 'Análise',
    weight: 10,
  },
  {
    id: 'sos',
    title: 'SOS — Shift Of Structure',
    description: 'Mudança de estrutura confirmando força',
    group: 'Entrada',
    weight: 15,
  },
  {
    id: 'entry-patterns',
    title: 'Padrões de entrada',
    description: 'Topo/Fundo duplo, OCO, Pullback',
    group: 'Entrada',
    weight: 10,
  },
  {
    id: 'hl-lh',
    title: 'Entrada em HL/LH',
    description: 'HL para compra, LH para venda',
    group: 'Entrada',
    weight: 10,
  },
  {
    id: 'engulfing-4h',
    title: 'Engulfing no 4H',
    description: 'Engulfing demonstra domínio de compradores/vendedores',
    group: 'Entrada',
    weight: 5,
  },
]

export const FOREX_PAIRS = [
  'EUR/USD',
  'GBP/USD',
  'USD/JPY',
  'USD/CHF',
  'USD/CAD',
  'AUD/USD',
  'NZD/USD',
  'EUR/GBP',
  'EUR/JPY',
  'EUR/CHF',
  'EUR/AUD',
  'EUR/NZD',
  'EUR/CAD',
  'GBP/JPY',
  'GBP/CHF',
  'GBP/AUD',
  'GBP/NZD',
  'GBP/CAD',
  'AUD/JPY',
  'AUD/NZD',
  'AUD/CHF',
  'AUD/CAD',
  'NZD/JPY',
  'NZD/CHF',
  'NZD/CAD',
  'CAD/JPY',
  'CAD/CHF',
  'CHF/JPY',
]

export const GRADES = [
  { threshold: 90, label: 'A+' },
  { threshold: 80, label: 'B+' },
  { threshold: 70, label: 'C+' },
  { threshold: 60, label: 'D+' },
  { threshold: 50, label: 'F+' },
]
